### ISSUE TITLE
On Garmin Vivoactive 3 Will not load

### ISSUE THREAD

**Issue by cardinalsyne** [vtrifonov-esfiddle/Meditate#1]
When I try to activate a session in meditate, the watch freezes on the IQ screen and shows an Exclamation point.  Just freezes.  App used to work, but upgraded software for the vivoactive 3

**Comment by vtrifonov-esfiddle** [comment]
With which version of the Meditate app it used to work and with which one it stopped?
Are you saying you upgraded the firmware of Vivoactive 3 to version 5.00? If yes did you try to install the latest version of the app (1.5.6)?
Have you tried to uninstall and install the app again?
I am currently using Meditate 1.5.6 on Vivoactive 3 firmware version 5.00 and cannot reproduce your problem.

**Comment by cardinalsyne** [comment]
I reset my vivoactive 3 and it works now.  Love the app. Thx
