### ISSUE TITLE
Porting to Instinct2

### ISSUE THREAD

**Issue by dmitrym0** [vtrifonov-esfiddle/Meditate#15]
Hello @vtrifonov-esfiddle,

I'd like to port Meditate to Instinct2 and would love to get your thoughts/feedback.

I naively assumed that it would be as simple as adding Instinct2 to the manifest and rebuilding. 

Unfortunately that is not the case; Instinct2 has 92k of memory; which is somewhat less than 105kb that is required at peak (at least in the simulator).

There is a [thread](https://forums.garmin.com/developer/connect-iq/f/discussion/290201/how-do-i-reduce-application-memory-size) on Garmin's ConnectIQ forums where I solicit some help in understanding how to reduce memory consumption. It looks like I have to really understand what's going on with the app before I can make a proper effort. My initial assumption was that removing some assets should be sufficient, but I wasn't successful.

In any case, if you're so inclined I'd love some thoughts on how to drop the extra 15k of memory. 

Otherwise, my plan is:

1. Play with the existing version in the simulator.
2. Roll up the functionality -- remove barrels.
3. Remove fonts/bitmaps.
4. Remove all but the basic functionality (hardcode meditation params, remove previous sessions, maybe more once I get a better understanding).

Thoughts?

PS: Forgot to thank you for making this app in the first place, and making it open source! Thanks and much appreciated 👍

**Comment by dliedke** [comment]
Hi @dmitrym0 , I ported the app for Garmin Forerunner 235 with reduced functionality. I think it might work fine in Instinct 2. You may find the code at:

https://github.com/dliedke/Meditate235

I could reduce the app to only 34k and it works fine in the device.

Thanks!

Daniel

**Comment by dmitrym0** [comment]
Hey @dliedke that's very kind of you! I'll give it a go on my instinct 2!

**Comment by dliedke** [comment]
Hi @dmitrym0 , I tried here the 235 version in the emulator and the app works. But there are some points to make it good:

- All colors should be removed (only white is supported)
- Texts location should be realigned because of screen resolution
- Test with real device is required

Thanks!

Daniel

**Comment by fl0schi** [comment]
Hey @dmitrym0,
could you build and install it successfully on a instinct2 model?
Thanks in advance and have a great week ahead.

**Comment by dmitrym0** [comment]
hey @fl0schi I don't think I did. It's been a few months. Do you have instinct2 as well?

**Comment by fl0schi** [comment]
@dmitrym0 hm..yep I have one as well since a few days and was looking for a "simple meditation app", like the one here in the repo. Until now I didn't spend much time in research/testing.

**Comment by dliedke** [comment]
Hi @dmitrym0, I created a version of meditate for Instinct2 watch.

Can you please test the compiled version from https://github.com/dliedke/MeditateInstinct2/tree/main/Compiled copying to your watch at /GARMIN/APPS folder?

Let me know the results.

Thanks!

**Comment by dliedke** [comment]
@fl0schi can you please help with the tests as well?

Thanks for your help!

**Comment by dmitrym0** [comment]
> Hi @dmitrym0, I created a version of meditate for Instinct2 watch.
> 
> Can you please test the compiled version from https://github.com/dliedke/MeditateInstinct2/tree/main/Compiled copying to your watch at /GARMIN/APPS folder?
> 
> Let me know the results.
> 
> Thanks!

Nicely done! What was your approach for reducing the app size?

Are there any instructions on how to get this onto the watch? It's been a while and I've forgotten how to do it.

**Comment by dliedke** [comment]
Thanks!

Instructions to install the application in the watch:

1) Connect watch to the PC using USB

2) Copy [MeditateInstinct2.prg](https://github.com/dliedke/MeditateInstinct2/blob/main/Compiled/MeditateInstinct2.prg) to your watch at /GARMIN/APPS folder

3) Try running the application on the watch.

In order to reduce app size I removed the HRV metrics, breath metrics, custom configurations and several screen in the summary. Also single language and using Connect IQ SDK 4.1.6 apps are compiled a little smaller as well.

**Comment by dliedke** [comment]
I requested to publish the app to the Garmin Connect IQ Store but it takes some days for them to approve. The link for the app in the store for regular installation will be https://apps.garmin.com/en-US/apps/45829a6e-f247-4261-9ae6-8587f557f397

**Comment by dmitrym0** [comment]
@dliedke got it running, so far so good! "Saving" fails, but I imagine it's because Garmin doesn't know what this data is about, until it gets published?

**Comment by dliedke** [comment]
Wow, good and bad news. I have no idea why saving is failing, it doesn't happen in the simulator. I saved the fit file and checked with fit viewer on the web and it was ok. I am not sure if it will be different in the store. But maybe you can try troubleshooting in your end if you have some time. Source code can be found at https://github.com/dliedke/MeditateInstinct2 I can also compile a debug version so we could check what is going on. Do you have any log file in the watch at \garmin\apps\logs?

**Comment by dliedke** [comment]
Can you please try the versions at https://github.com/dliedke/MeditateInstinct2/tree/main/Compiled/Debug ? It is with a simpler activity name without emoticon that might be causing the issue. Also there is a debug version there as well.

**Comment by dliedke** [comment]
And really appreciate your help with these testing and troubleshooting @dmitrym0! 😀🙏

**Comment by dliedke** [comment]
This is how I am creating the activity, but these enums are available since API 1.0.0:

`class FitSessionSpec {
		
		static function createCardio(sessionName) {
			return {
                 :name => sessionName,                              
                 :sport => ActivityRecording.SPORT_TRAINING,      
                 :subSport => ActivityRecording.SUB_SPORT_GENERIC
                };
		}
	}`

https://developer.garmin.com/connect-iq/api-docs/Toybox/ActivityRecording.html#Sport1-module

**Comment by dmitrym0** [comment]
I think something else is going on, I opened up the Connect app on my iPhone and my meditation sessions were in there. I'll give the debug version a go as well. 

Out of curiosity, is there any room in there to re-introduce some configuration? For instance I'd love to be able to set the "reminder" period at 2 minutes since that's what I've been using for a while with other apps.

**Comment by dliedke** [comment]
Actually it is hard coded for a fast small vibration every 5min, then a longer vibration at the end. 
What happened in the watch when you saved? Did the HR chart appear?

**Comment by dmitrym0** [comment]
I guess the easiest way is for me to change it locally to 2 minutes and rebuild?

The HR chart appeared, I clicked the save button and then "save failed" appeared. But it did show up on my phone.

**Comment by dliedke** [comment]
Ok, I can build a special version for you. The official version is approved and published in the Garmin Connect IQ store.

**Comment by dliedke** [comment]
There you go: https://github.com/dliedke/MeditateInstinct2/blob/main/Compiled/MeditateWarn2MinBeforeEndingSession.prg

If you like other customizations you may search for "Warn user" in the source code, I left commented where I placed the 2min warning before ending the session.

About the save failed issue there is not much I can do. If the activity is showing in Garmin Connect and also the HR chart is displayed, I think it is ok. Other users did not report any problem yet.

Official version is published to https://apps.garmin.com/en-US/apps/45829a6e-f247-4261-9ae6-8587f557f397

Thanks @dmitrym0 you may close this issue.

**Comment by dmitrym0** [comment]
Amazing work @dliedke thanks for the custom build! 

I just wish that Garmin gave us more memory to work with so we could have the HRV stats and all the other niceties.

**Comment by dliedke** [comment]
No worries, when you buy your next Garmin watch it will run the full version! 
https://apps.garmin.com/en-US/apps/c5fc5ea5-7d12-4fb9-be9c-701663a39db7#0

Thanks a lot @dmitrym0 for the motivation to create this port!
