### ISSUE TITLE
seeing "Waiting HRV" on forerunner 245 music

### ISSUE THREAD

**Issue by aron-bordin** [vtrifonov-esfiddle/Meditate#3]
hi!
I'm not able to use the app, I'm always getting the message above. I tried to reinstall it and to restart the watch, but not working here :(

**Comment by vtrifonov-esfiddle** [comment]
You can try the following:
- move the watch to a slightly different position on your wrist
- tighten the strap
- minimise wrist movement

Please see the [user guide](https://github.com/vtrifonov-esfiddle/Meditate/blob/master/UserGuide.md#3-picking-a-session) for details about the indicator.
If you don't care about the HRV metrics you can start a session. Then HRV could either be entirely or partially missing from the results in ConnectIQ.
