### ISSUE TITLE
Cannot change time of meditation

### ISSUE THREAD

**Issue by BerglindJons** [vtrifonov-esfiddle/Meditate#4]
When swiping up and down to change the time, nothing happens. The screens seems to flicker like it is switching between some states but the time remains as 00:10:00. See image attached. 
![15959545285355872112426699745784](https://user-images.githubusercontent.com/13417353/88695369-158e2b80-d102-11ea-94bb-237620d3f0fe.jpg)

How can this be fixed?

**Comment by vtrifonov-esfiddle** [comment]
Swiping up/down is for changing to different session. You need to toggle the session menu. Please see the [user guide](https://github.com/vtrifonov-esfiddle/Meditate/blob/master/UserGuide.md#2-configuring-a-session)
