### ISSUE TITLE
alerts overlap - can / should they work in sequence?

### ISSUE THREAD

**Issue by gazzawazza** [vtrifonov-esfiddle/Meditate#6]
hi there

firstly, tyvm for developing this app. It's appreciated and needed on the platform.

Don't know if this is a bug or wasn't designed to work like this or might be a feature request.

I've tried to create a meditation session which has a warm-up period, followed by a number of equal length periods (mindfulness of breathing, just in case you know it).

Goal is:

10 mins 'settling' period, followed by 4 x 6 mins periods

I've configured:

time = 34 mins
alert 1 = one off of 10 mins
alert 2 = repeat every 6 mins

This results in the alerts stacking, rather than firing in sequence i.e. the alerts are **not** at the following minutes 10, 6, 6, 6, 6 but 6, 4, 2, 6, 6, 6

At least i'm going on the alert graphic for the session (see photo). One sees the 10 min alert, then when you add the repeating one, you get an alert appearing before the 10 min one and then shortly after.

![20210109_205346](https://user-images.githubusercontent.com/3268066/104108522-35cf3280-52bd-11eb-85c4-948311f57795.jpg)

Am i doing something wrong?

regards,

Gary

**Comment by vtrifonov-esfiddle** [comment]
Hi Gary,

The behaviour you discribe is intended to work as you see it. 
- One-off alerts fire at the specified time since the start of the session. 
- Repetitive alerts fire every MM:SS since the start of the session

Assuming you want to do your warm-up and and mindfulness practice in one session you can configure the following alerts
- 1x one off at 10:00
- individual one off alerts at 16:00, 22:00, 28:00
- when the session ends you'll get the session end alert
- consider using different colours for different interval alerts

Alternatively assuming you want to treat warm-up and the mindfulness as separate sessions consider using Mult-Session mode. Then you can configure:
1. one 10 minute session for warm-up 
2. another 24 minute session for your mindfulness with repetitive alert every 6 minutes.

After 1. finishes select 2 and start it.

Have a look at the [user guide](https://github.com/vtrifonov-esfiddle/Meditate/blob/master/UserGuide.md#how-to-use)

**Comment by gazzawazza** [comment]
> 
> 
> Hi Gary,
> 
> The behaviour you describe is intended to work as you see it.
> 
>     * One-off alerts fire at the specified time since the start of the session.
> 
>     * Repetitive alerts fire every MM:SS since the start of the session
> 
> 
> Assuming you want to do your warm-up and and mindfulness practice in one session you can configure the following alerts
> 
>     * 1x one-off at 10:00
> 
>     * individual one-off alerts at 16:00, 22:00, 28:00
> 
>     * when the session ends you'll get the session end alert
> 
>     * consider using different colours for different interval alerts
> 
> 
> Alternatively assuming you want to treat warm-up and the mindfulness as separate sessions consider using Mult-Session mode. Then you can configure:
> 
>     1. one 10 minute session for warm-up
> 
>     2. another 24 minute session for your mindfulness with repetitive alert every 6 minutes.
> 
> 
> After 1. finishes select 2 and start it.
> 
> Have a look at the [user guide](https://github.com/vtrifonov-esfiddle/Meditate/blob/master/UserGuide.md#how-to-use)

Hi there

thanks for the response and the explanation.

It's a shame that you have the very useful ability to replicate intervals but can't use that unless all your intervals can run from the beginning of the session / are the same length.

Just to reassure you, i did actually have a look at the guide before i posted here - it's got useful content in it but i didn't see the bit about intervals starting from the beginning.

Regarding multi-session mode, i assume you can't tie two sessions together i.e. run sequentially, without a manual start?

Seems like this mode kinda suspends the save function and allows you to pick more sessions?

Maybe make a function where you can create a meditation set (a group of sessions), where you can define different meditation sessions to run in that set? Like a playlist. Just a thought.



regards,

Gary

**Comment by vtrifonov-esfiddle** [comment]
> Regarding multi-session mode, i assume you can't tie two sessions together i.e. run sequentially, without a manual start?
Yes. You need to manually start the next session.

> Seems like this mode kinda suspends the save function and allows you to pick more sessions?
Each session is saved/discarded separately. They will appear as separate activities in Connect IQ

> Maybe make a function where you can create a meditation set (a group of sessions), where you can define different meditation sessions to run in that set? Like a playlist. Just a thought.
That is currently outside the scope of the app and I do not plan to implement it.

> It's a shame that you have the very useful ability to replicate intervals but can't use that unless all your intervals can run from the beginning of the session / are the same length.

If you want to change the intervals behaviour your best bet is to fork the repo and do it the way you like. I am not interested into changing this.

**Comment by gazzawazza** [comment]
> 
> 
> > Regarding multi-session mode, i assume you can't tie two sessions together i.e. run sequentially, without a manual start?
> 
> Yes. You need to manually start the next session.
> 
> > Seems like this mode kinda suspends the save function and allows you to pick more sessions?
> 
> Each session is saved/discarded separately. They will appear as separate activities in Connect IQ
> 
> > Maybe make a function where you can create a meditation set (a group of sessions), where you can define different meditation sessions to run in that set? Like a playlist. Just a thought.
> 
> That is currently outside the scope of the app and I do not plan to implement it.
> 
> > It's a shame that you have the very useful ability to replicate intervals but can't use that unless all your intervals can run from the beginning of the session / are the same length.
> 
> If you want to change the intervals behaviour your best bet is to fork the repo and do it the way you like. I am not interested into changing this.

ok
