### ISSUE TITLE
Stress value

### ISSUE THREAD

**Issue by rob-miller** [vtrifonov-esfiddle/Meditate#7]
This is a request for more info on the ‘percent stress’ result.  It seems to be inversely correlated with actual stress, i.e. lower percentage matches lower hrv. I suspect this is some reading supplied by Garmin, can you link to more info perhaps from them?  Thank you

**Comment by vtrifonov-esfiddle** [comment]
This is experimental metric not related to Garmin's stress. For details how it is calculated have a look here:
- https://github.com/vtrifonov-esfiddle/Meditate/blob/master/HrvAlgorithms/sources/activity/stress/StressMonitor.mc
- https://github.com/vtrifonov-esfiddle/Meditate/blob/master/HrvAlgorithms/sources/activity/stress/HrPeaksWindow.mc

It is essentially the average HR Peak from the **HR Peaks 10 Sec Window(bpm)** graph divided by the HR Peaks - Min HR
![image](https://user-images.githubusercontent.com/15705284/112211533-ea69c680-8c13-11eb-807a-4aa92a21423e.png)

**Comment by gazzawazza** [comment]
I'm interested in this value, so was trying to translate this into something i can understand.

You're trying to show, as a percentage, HR fluctuations above minimum, as a proportion of average total HR

So it's the average HR (snapshots every 10s) e.g. 105 (just guessing from the graph)

divided by kinda spikes in HR or rather the difference in HR spikes (above minimum). Presumably an average then?

e.g. 105 / (105-99)
