### ISSUE TITLE
Fenix 5s APAC - can't change Global Settings

### ISSUE THREAD

**Issue by tamari-oz** [vtrifonov-esfiddle/Meditate#9]
Hi,
Thanks for this app. I really like it.
The 2 annoyances I have are that I can't pause a session and I can't change the global settings (I assume the VA 3 has touch screen while Fenix 5 don't.

Is it possible to implement changes to allow these?

Thanks!

**Comment by vtrifonov-esfiddle** [comment]
You can change the global settings by pressing the menu button on your watch. 
For the purposes of pausing you can use the [Multi-Session mode](https://github.com/vtrifonov-esfiddle/Meditate/blob/master/UserGuide.md#43-multi-session). When you want to pause just stop the current session. When you are ready to continue just start a new session.
Please have a look at the [user guide](https://github.com/vtrifonov-esfiddle/Meditate/blob/master/UserGuide.md#how-to-use).

**Comment by tamari-oz** [comment]
Thanks! I was not aware I can long press **Menu** again to change the menu.
